"""Parity: the onset-coactivity assessment against its MATLAB original.

Same 1e-9 bar as the six detectors, and for the same reason — the algorithm
draws only ``rand``, which is bit-compatible with ``RandomState``
(FOUNDATIONS §2). Reference generated by ``tools/matlab_ref/gen_ref_assess.m``
from the **synthetic** fixture only.

Every scalar the MATLAB emits is compared, not just the headline: a port that
matches ``coact_excess`` while disagreeing on ``span_med`` is a port that would
mis-parameterize the generator, which is the whole reason this exists.
"""

from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path

import numpy as np
import pytest

from bugarach.assess import assess_coactivity
from bugarach.store import load_slice

FIX = Path(__file__).parent / "fixtures"
REF = FIX / "ref_assess_synth.json"

# Everything the MATLAB dumps. Booleans and counts compare exactly; floats to 1e-9.
FLOAT_FIELDS = (
    ("win_dur", "win_dur"), ("roiRate_med", "roi_rate_med"),
    ("roiRate_mean", "roi_rate_mean"), ("evrate_permin", "ev_rate_permin"),
    ("width_med", "width_med"), ("width_iqr", "width_iqr"),
    ("coact_excess", "coact_excess"), ("obs_mass", "obs_mass"),
    ("null_mass", "null_mass"), ("jit_obs", "jit_obs"),
    ("jit_null", "jit_null"), ("jit_excess", "jit_excess"),
    ("partN_obs", "part_n_obs"), ("peak_med", "peak_med"),
    ("span_med", "span_med"), ("clusters_permin", "clusters_permin"),
)
EXACT_FIELDS = (
    ("min_rois", "min_rois"), ("meets_floor", "meets_floor"),
    ("n_roi", "n_roi"), ("n_events_win", "n_events_win"),
    ("n_coact_bins", "n_coact_bins"), ("jit_defined", "jit_defined"),
    ("n_clusters_obs", "n_clusters_obs"), ("n_clusters_null", "n_clusters_null"),
)


def _baseline_slice():
    """The fixture with its region named, as the reference generator names it.

    The committed fixture's region is unnamed, and the MATLAB selects its window
    through `if2_region_windows`, which classifies by name. Naming it here runs
    the port through bugarach's own `region_windows`, so the aCa5z trim is
    compared too rather than assumed — the MATLAB trims 4520 s down to its final
    1200 s, and a port that skipped the trim would analyse 3.8x the data and still
    match nothing.
    """
    s = load_slice(FIX / "synth_fastcal_s1.mat")
    s = deepcopy(s)
    for r in s.regions:
        r.name = "baseline"
    return s


def _cases():
    if not REF.exists():
        pytest.skip(f"{REF.name} not generated (needs MATLAB + interface2)")
    return json.load(REF.open())["cases"]


@pytest.mark.parametrize("ci", range(4))
def test_assessment_matches_matlab(ci):
    cases = _cases()
    case = cases[ci]
    o = case["opts"]

    got = assess_coactivity(
        _baseline_slice(),
        stream=o["stream"],
        region="baseline",
        min_rois=tuple(np.atleast_1d(o["min_rois"]).astype(int).tolist()),
        bin_width_sec=float(o["binw_sec"]),
        wm_factor=float(o["Wm_factor"]),
        merge_bins=int(o["merge_bins"]),
        n_surrogates=int(o["n_surr"]),
        rng_seed=int(o["rng_seed"]),
    )

    assert len(got) == len(case["recs"])
    for ref, mine in zip(case["recs"], got):
        for mkey, pkey in EXACT_FIELDS:
            assert getattr(mine, pkey) == ref[mkey], (
                f"case {ci} K={ref['min_rois']}: {pkey} "
                f"{getattr(mine, pkey)!r} != MATLAB {ref[mkey]!r}")
        for mkey, pkey in FLOAT_FIELDS:
            r, m = ref[mkey], getattr(mine, pkey)
            # jsonencode maps NaN to null (FOUNDATIONS §2) — null must mean NaN
            # here, never a missing field silently comparing equal.
            if r is None:
                assert not np.isfinite(m), f"case {ci}: {pkey} should be NaN, got {m}"
                continue
            assert np.isfinite(m), f"case {ci}: {pkey} is {m}, MATLAB gave {r}"
            assert abs(float(m) - float(r)) <= 1e-9 * max(1.0, abs(float(r))), (
                f"case {ci} K={ref['min_rois']}: {pkey} "
                f"{m!r} != MATLAB {r!r}")


def test_jit_defined_is_not_the_same_as_jit_obs_being_finite():
    """The trap the module docstring warns about, pinned.

    `jit_obs` can be a perfectly finite number while the comparison it belongs to
    does not exist, because the surrogate ensemble formed no cluster at that K.
    A caller reading `jit_obs` without checking `jit_defined` gets a number with
    no null behind it.
    """
    recs = assess_coactivity(_baseline_slice(), stream="fast", region="baseline",
                             min_rois=(3, 8), n_surrogates=40)
    by_k = {r.min_rois: r for r in recs}
    assert by_k[3].jit_defined
    high = by_k[8]
    if not high.jit_defined:
        assert np.isfinite(high.jit_obs) or np.isnan(high.jit_obs)
        assert np.isnan(high.jit_null) or high.n_clusters_null == 0


def test_short_window_returns_nan_rather_than_a_number():
    """A window under the floor yields `meets_floor=False` and NaN measures — not
    a small number that reads like a quiet recording."""
    s = _baseline_slice()
    recs = assess_coactivity(s, stream="fast", window=(0.0, 100.0),
                             min_rois=(3,), n_surrogates=5)
    assert len(recs) == 1
    assert not recs[0].meets_floor
    assert np.isnan(recs[0].coact_excess)


def test_roi_order_does_not_change_the_assessment():
    """Coactivity counts ROIs, so permuting them must change nothing.

    Cheap, and it pins the property the whole learned-detector design rests on:
    ROI index carries no information.
    """
    s = _baseline_slice()
    a = assess_coactivity(s, stream="fast", region="baseline", min_rois=(4,),
                          n_surrogates=30)[0]

    shuffled = deepcopy(s)
    st = shuffled.streams["fast"]
    perm = np.random.RandomState(7).permutation(st.n_rois)
    for f in ("locs", "amp", "width", "t50rise"):
        v = getattr(st, f, None)
        if v is not None and len(v) == perm.size:
            setattr(st, f, [v[i] for i in perm])
    b = assess_coactivity(shuffled, stream="fast", region="baseline",
                          min_rois=(4,), n_surrogates=30)[0]

    assert a.n_coact_bins == b.n_coact_bins
    assert a.obs_mass == pytest.approx(b.obs_mass, abs=1e-12)
    assert a.n_clusters_obs == b.n_clusters_obs
    assert a.span_med == pytest.approx(b.span_med, abs=1e-12, nan_ok=True)
