function gen_ref_assess(inFile, outFile)
%gen_ref_assess  Reference outputs for the bugarach onset-coactivity assessment.
%   Builds an event_store struct from the exported trains, writes it to a temp
%   .mat (measure_coordination_timescale takes a PATH, not a struct), and runs it
%   over several cases. Dumps every scalar measure so the port is compared on all
%   of them rather than on the headline alone.
%
%   The region is named 'baseline' on purpose: measure_coordination_timescale
%   selects its window through if2_region_windows, which classifies by name, and
%   the committed fixture's region is unnamed. The window each case actually used
%   is dumped alongside the measures, so the Python side asserts on the same span
%   instead of assuming it.

d = load(inFile);

nreg = numel(d.regions_start);
regions = struct('name', {}, 'slot', {}, 'start_sec', {}, 'end_sec', {});
for k = 1:nreg
    regions(k).name = 'baseline';
    regions(k).slot = '';
    regions(k).start_sec = d.regions_start(k);
    regions(k).end_sec = d.regions_end(k);
end

es = struct('slice_id', d.slice_id, ...
            'fast', struct('locs', {d.fast_locs}, 't50rise', {d.fast_t50rise}, ...
                           'width', {d.fast_width}), ...
            'slow', struct('locs', {d.slow_locs}, 't50rise', {d.slow_t50rise}, ...
                           'width', {d.slow_width}), ...
            'regions', regions);

tmp = [tempname '.mat'];
fast = es.fast; slow = es.slow; slice_id = es.slice_id; %#ok<NASGU>
save(tmp, 'fast', 'slow', 'regions', 'slice_id', '-v7');
c = onCleanup(@() delete(tmp));

CASES = { ...
    struct('stream','fast','binw_sec',1,   'n_surr',200, 'rng_seed',20260722, ...
           'merge_bins',2, 'Wm_factor',1.5, 'min_rois',[3 4 6 8]), ...
    struct('stream','fast','binw_sec',2,   'n_surr',120, 'rng_seed',7, ...
           'merge_bins',3, 'Wm_factor',1.0, 'min_rois',[3 5]), ...
    struct('stream','slow','binw_sec',2,   'n_surr',150, 'rng_seed',20260722, ...
           'merge_bins',2, 'Wm_factor',1.5, 'min_rois',[3 4]), ...
    struct('stream','fast','binw_sec',0.5, 'n_surr',80,  'rng_seed',101, ...
           'merge_bins',1, 'Wm_factor',2.0, 'min_rois',[4]) };

out = struct('cases', {{}});
for ci = 1:numel(CASES)
    o = CASES{ci};
    o.region = 'baseline';
    recs = measure_coordination_timescale(tmp, o);

    R = struct('opts', o, 'recs', {{}});
    for ki = 1:numel(recs)
        r = recs(ki);
        R.recs{end+1} = struct( ...
            'min_rois',      r.min_rois, ...
            'meets_floor',   r.meets_floor, ...
            'win_dur',       r.win_dur, ...
            'n_roi',         r.n_roi, ...
            'n_events_win',  r.n_events_win, ...
            'roiRate_med',   r.roiRate_med, ...
            'roiRate_mean',  r.roiRate_mean, ...
            'evrate_permin', r.evrate_permin, ...
            'width_med',     r.width_med, ...
            'width_iqr',     r.width_iqr, ...
            'coact_excess',  r.coact_excess, ...
            'obs_mass',      r.obs_mass, ...
            'null_mass',     r.null_mass, ...
            'n_coact_bins',  r.n_coact_bins, ...
            'jit_obs',       r.jit_obs, ...
            'jit_null',      r.jit_null, ...
            'jit_excess',    r.jit_excess, ...
            'jit_defined',   r.jit_defined, ...
            'partN_obs',     r.partN_obs, ...
            'peak_med',      r.peak_med, ...
            'span_med',      r.span_med, ...
            'n_clusters_obs',  r.n_clusters_obs, ...
            'n_clusters_null', r.n_clusters_null, ...
            'clusters_permin', r.clusters_permin);
    end
    out.cases{end+1} = R;
end

% jsonencode maps NaN/Inf to null (FOUNDATIONS §2) — the Python side reads null
% back as NaN rather than treating it as a missing field.
fid = fopen(outFile, 'w');
fwrite(fid, jsonencode(out, 'PrettyPrint', true));
fclose(fid);
fprintf('wrote %s\n', outFile);
end
