#!/usr/bin/env python3
"""Draw the two data figures for the field-size proposal, from the probe's own JSON.

    python tools/make_field_size_figures.py [--out DIR] [--also DIR]

Reads `field_size.json` (written by `tools/probe_field_size.py`) and emits two SVG
fragments. **No number in either figure is typed here** — that is the whole reason
this is a tool and not hand-drawn markup, and it is the rule the ratio-tube probe's
first write-up broke by quoting percentages it had not recomputed.

The fragments carry no `<style>` block and set colour only through CSS custom
properties the host page defines, so one figure reads correctly in a light page and
a dark one. That is draughtsman's rule for the front-page architecture drawing
(`third_party/draughtsman/render.py`) and it applies for the same reason here.

⚠ These are the two figures that draw MEASURED quantities. The mechanism diagrams on
the page are schematics, hand-drawn, and marked as such — a schematic generated by a
tool would claim a provenance it does not have.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

W = 880           # figure width, in SVG user units
XLO, XHI = 8.0, 1300.0        # field-size axis, cells


def xpos(n: float, left: float, right: float) -> float:
    """Log position of a field size on an axis running left..right."""
    lo, hi = math.log10(XLO), math.log10(XHI)
    return left + (right - left) * (math.log10(n) - lo) / (hi - lo)


def esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


# ---------------------------------------------------------------- figure 1
def fig_field(data: dict) -> str:
    """Where the recordings actually sit on the field-size axis."""
    left, right = 128.0, W - 30.0
    o = [f'<svg viewBox="0 0 {W} 232" role="img" '
         f'aria-label="Field size per recording in two corpora, log axis, '
         f'9 to 1050 cells">']
    ticks = [10, 20, 50, 100, 200, 500, 1000]
    base = 186
    o.append(f'<line class="ax" x1="{left}" y1="{base}" x2="{right}" y2="{base}"/>')
    for t in ticks:
        x = xpos(t, left, right)
        o.append(f'<line class="ax" x1="{x:.1f}" y1="{base}" x2="{x:.1f}" y2="{base+5}"/>')
        o.append(f'<text class="tick" x="{x:.1f}" y="{base+18}" '
                 f'text-anchor="middle">{t}</text>')
    o.append(f'<text class="tick" x="{(left+right)/2:.1f}" y="{base+36}" '
             f'text-anchor="middle">cells in the field (log scale)</text>')

    rows = [(data["corpora"][0], 62.0, "a"), (data["corpora"][1], 126.0, "b")]
    for c, y, cls in rows:
        lo, p25, med = c["n_roi_min"], c["n_roi_p25"], c["n_roi_median"]
        p75, hi = c["n_roi_p75"], c["n_roi_max"]
        xl, xr = xpos(lo, left, right), xpos(hi, left, right)
        bl, br = xpos(p25, left, right), xpos(p75, left, right)
        xm = xpos(med, left, right)
        o.append(f'<line class="whisk {cls}" x1="{xl:.1f}" y1="{y}" x2="{xr:.1f}" y2="{y}"/>')
        for x in (xl, xr):
            o.append(f'<line class="whisk {cls}" x1="{x:.1f}" y1="{y-8}" '
                     f'x2="{x:.1f}" y2="{y+8}"/>')
        o.append(f'<rect class="box {cls}" x="{bl:.1f}" y="{y-13}" '
                 f'width="{max(br-bl,2):.1f}" height="26" rx="2"/>')
        o.append(f'<line class="med {cls}" x1="{xm:.1f}" y1="{y-15}" '
                 f'x2="{xm:.1f}" y2="{y+15}"/>')
        o.append(f'<text class="lab" x="{left-14}" y="{y-2}" text-anchor="end">'
                 f'{esc(c["short"])}</text>')
        o.append(f'<text class="tick" x="{left-14}" y="{y+13}" text-anchor="end">'
                 f'{c["n_rows"]} windows</text>')
        o.append(f'<text class="tick {cls}" x="{xl:.1f}" y="{y-20}" '
                 f'text-anchor="middle">{lo}</text>')
        o.append(f'<text class="tick {cls}" x="{xm:.1f}" y="{y+30}" '
                 f'text-anchor="middle">median {med} cells</text>')
        o.append(f'<text class="tick {cls}" x="{xr:.1f}" y="{y-20}" '
                 f'text-anchor="middle">{hi}</text>')

    # the two sizes Tony named, marked on the axis and nowhere near each other
    for n, note in ((13, "13 cells"), (50, "50 cells")):
        x = xpos(n, left, right)
        o.append(f'<line class="callout" x1="{x:.1f}" y1="{base-8}" '
                 f'x2="{x:.1f}" y2="{base}"/>')
        o.append(f'<text class="tick hi" x="{x:.1f}" y="{base-13}" '
                 f'text-anchor="middle">{esc(note)}</text>')
    o.append("</svg>")
    return "\n".join(o)


# ---------------------------------------------------------------- figure 2
def fig_floor(data: dict) -> str:
    """The chance floor against the two rules on offer, and what each rule costs."""
    H = 330
    o = [f'<svg viewBox="0 0 {W} {H}" role="img" aria-label="Panel a, the '
         f'co-active-cell floor against field size, with a fixed-count rule and a '
         f'fixed-fraction rule; panel b, how far each rule misses its false-alarm '
         f'budget">']
    # -- panel a: k against N, log-log
    al, ar, at, ab = 56.0, 408.0, 40.0, 240.0
    ylo, yhi = 1.0, 140.0          # cells, log

    def ya(k):
        return ab - (ab - at) * (math.log10(k) - math.log10(ylo)) / (
            math.log10(yhi) - math.log10(ylo))

    def xa(n):
        return xpos(n, al, ar)

    o.append(f'<text class="pan" x="{al-34}" y="{at-16}">a</text>')
    o.append(f'<text class="lab" x="{al-14}" y="{at-16}">how many cells it takes</text>')
    o.append(f'<line class="ax" x1="{al}" y1="{ab}" x2="{ar}" y2="{ab}"/>')
    o.append(f'<line class="ax" x1="{al}" y1="{at}" x2="{al}" y2="{ab}"/>')
    for t in (10, 100, 1000):
        x = xa(t)
        o.append(f'<line class="ax" x1="{x:.1f}" y1="{ab}" x2="{x:.1f}" y2="{ab+5}"/>')
        o.append(f'<text class="tick" x="{x:.1f}" y="{ab+18}" text-anchor="middle">{t}</text>')
    for t in (1, 3, 10, 30, 100):
        y = ya(t)
        o.append(f'<line class="ax" x1="{al-5}" y1="{y:.1f}" x2="{al}" y2="{y:.1f}"/>')
        o.append(f'<text class="tick" x="{al-9}" y="{y+3.5:.1f}" text-anchor="end">{t}</text>')
    o.append(f'<text class="tick" x="{(al+ar)/2:.1f}" y="{ab+34}" '
             f'text-anchor="middle">cells in the field</text>')
    o.append(f'<text class="tick" transform="translate({al-34},{(at+ab)/2:.1f}) rotate(-90)" '
             f'text-anchor="middle">co-active cells</text>')

    # the two rules, drawn first so the measured curves sit on top
    k_count = data["threshold_carried_from_32_cells"][0]["calibrated_k"]
    frac = k_count / 32.0
    o.append(f'<line class="rule-count" x1="{xa(XLO):.1f}" y1="{ya(k_count):.1f}" '
             f'x2="{xa(XHI):.1f}" y2="{ya(k_count):.1f}"/>')
    pts = " ".join(f"{xa(n):.1f},{ya(max(frac*n, ylo)):.1f}"
                   for n in (9, 20, 50, 140, 400, 1300) if frac * n <= yhi)
    o.append(f'<polyline class="rule-frac" points="{pts}"/>')

    for i, f in enumerate(data["detection_floor"]):
        cls = "a" if i == 0 else "b"
        pts = " ".join(f"{xa(r['n_roi']):.1f},{ya(r['k_floor_cells']):.1f}"
                       for r in f["curve"])
        o.append(f'<polyline class="curve {cls}" points="{pts}"/>')
        last = f["curve"][-1]
        dy = -10 if cls == "b" else 15
        o.append(f'<text class="tick {cls}" x="{xa(last["n_roi"]):.1f}" '
                 f'y="{ya(last["k_floor_cells"]) + dy:.1f}" text-anchor="end">'
                 f'{esc(f["short"])}</text>')
    o.append(f'<text class="tick dim" x="{xa(110):.1f}" y="{ya(k_count)+15:.1f}" '
             f'text-anchor="middle">a fixed count, {k_count} cells</text>')
    o.append(f'<text class="tick dim" x="{xa(30):.1f}" y="{ya(1.15):.1f}" '
             f'text-anchor="middle">a fixed {frac*100:.1f}% of the field</text>')

    # -- panel b: how far off budget each rule lands
    bl_, br_, bt, bb = 556.0, W - 30.0, 40.0, 240.0
    lo_e, hi_e = -90.0, 10.0       # decades away from the budget

    def yb(ratio):
        e = math.log10(ratio) if ratio > 0 else lo_e
        e = max(lo_e, min(hi_e, e))
        return bb - (bb - bt) * (e - lo_e) / (hi_e - lo_e)

    def xb(n):
        return xpos(n, bl_, br_)

    o.append(f'<text class="pan" x="{bl_-34}" y="{bt-16}">b</text>')
    o.append(f'<text class="lab" x="{bl_-14}" y="{bt-16}">'
             f'how far each rule misses its budget</text>')
    o.append(f'<line class="ax" x1="{bl_}" y1="{bb}" x2="{br_}" y2="{bb}"/>')
    o.append(f'<line class="ax" x1="{bl_}" y1="{bt}" x2="{bl_}" y2="{bb}"/>')
    for t in (10, 100, 1000):
        x = xb(t)
        o.append(f'<line class="ax" x1="{x:.1f}" y1="{bb}" x2="{x:.1f}" y2="{bb+5}"/>')
        o.append(f'<text class="tick" x="{x:.1f}" y="{bb+18}" text-anchor="middle">{t}</text>')
    for e in (0, -20, -40, -60, -80):
        y = yb(10.0 ** e)
        lbl = "on budget" if e == 0 else f"{e} decades"
        o.append(f'<line class="ax" x1="{bl_-5}" y1="{y:.1f}" x2="{bl_}" y2="{y:.1f}"/>')
        o.append(f'<text class="tick" x="{bl_-9}" y="{y+3.5:.1f}" text-anchor="end">{lbl}</text>')
    o.append(f'<line class="zero" x1="{bl_}" y1="{yb(1.0):.1f}" '
             f'x2="{br_}" y2="{yb(1.0):.1f}"/>')
    o.append(f'<text class="tick" x="{(bl_+br_)/2:.1f}" y="{bb+34}" '
             f'text-anchor="middle">cells in the field</text>')
    o.append(f'<text class="tick" transform="translate({bl_-76},{(bt+bb)/2:.1f}) '
             f'rotate(-90)" text-anchor="middle">chance firings vs budget</text>')

    car = data["threshold_carried_from_32_cells"][0]
    for key, cls, name in (("count_rule_fa_ratio", "rule-count", "a fixed count"),
                           ("fraction_rule_fa_ratio", "rule-frac", "a fixed fraction")):
        pts = " ".join(f"{xb(r['n_roi']):.1f},{yb(r[key]):.1f}" for r in car["by_n_roi"])
        o.append(f'<polyline class="{cls} thick" points="{pts}"/>')
    o.append(f'<text class="tick dim" x="{xb(1250):.1f}" '
             f'y="{yb(car["by_n_roi"][-1]["count_rule_fa_ratio"])-10:.1f}" '
             f'text-anchor="end">a fixed count &#8212; fires far too often</text>')
    o.append(f'<text class="tick dim" x="{xb(160):.1f}" y="{yb(3e-56):.1f}" '
             f'text-anchor="middle">a fixed fraction &#8212; goes deaf</text>')
    o.append(f'<line class="callout" x1="{xb(32):.1f}" y1="{yb(1.0)+4:.1f}" '
             f'x2="{xb(32):.1f}" y2="{bb-20:.1f}" stroke-dasharray="3 3"/>')
    o.append(f'<text class="tick hi" x="{xb(32):.1f}" y="{bb-8:.1f}" '
             f'text-anchor="middle">both rules are set here</text>')

    # -- the pivot, stated once across the bottom
    o.append(f'<text class="lab" x="{al-14}" y="{H-24}">'
             f'A statistic standardized against the field’s own null sits on the '
             f'budget at every size &#8212; the flat line in b, and the measured curves in a.</text>')
    o.append("</svg>")
    return "\n".join(o)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--json", default=str(REPO / "docs/learned/field_size.json"))
    ap.add_argument("--out", default=None, help="where the SVGs go (default: darkroom)")
    ap.add_argument("--also", default=None, help="a second copy, usually the repo")
    args = ap.parse_args()

    data = json.loads(Path(args.json).read_text())
    figs = {"field_size_fig1.svg": fig_field(data),
            "field_size_fig2.svg": fig_floor(data)}

    out_dir = args.out
    if out_dir is None:
        try:
            from bugarach.paths import darkroom
            out_dir = str(darkroom())
        except Exception:                                   # pragma: no cover
            out_dir = str(REPO / "docs" / "proposals" / "figures")
    for d in [out_dir] + ([args.also] if args.also else []):
        Path(d).mkdir(parents=True, exist_ok=True)
        for name, svg in figs.items():
            (Path(d) / name).write_text(svg + "\n")
            print(Path(d) / name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
